### PR TITLE
remove net45 and netcoreapp1.1

### PR DESCRIPTION
**Pull request by SimonCropp**
This is just an opinion PR on my part. 

 * netcore 1.1 support ended in July https://dotnet.microsoft.com/platform/support/policy/dotnet-core
 * net45 support ended in 2016-01-12 https://en.wikipedia.org/wiki/.NET_Framework_version_history

feel free to close if u want to keep those targets

### CODE REVIEW

**Comment by SimonCropp** [comment]
mainly since i couldnt build with netcoreapp1.1 in the mix (at least not without installing more things)

**Comment by nblumhardt** [comment]
Thanks for the PR! It's tempting, but having some support for <sigh> unsupported 😅 platforms is important for Serilog, and I think the console sink is one of the bare-minimum set of sinks we need to make that story realistic.

While it's not hurting us _too_ badly (there's not a huge amount of active development needed in this repo right now) I think we should maintain the status-quo, here. But definitely could be reconsidered in the future 👍

**Comment by SimonCropp** [comment]
no worries at all. did u want to take the netcore 2.2 bits?

**Comment by nblumhardt** [comment]
Sounds good 👍

**Pull request closed without merging**
