### PR TITLE
Support NO_COLOR environment variable

### LINKED ISSUE #153: Please support NO_COLOR environment variable
We use Serilog directly in a number of systems, and indirectly via some [Nuke build](https://github.com/nuke-build/nuke) scripts -- Nuke uses Serilog itself.

We enjoy colored console logging when running interactively, but this same code is often run in Automated Builds (TeamCity, GitHub actions, etc) where stdout is captured by the build system - sometimes indirectly through `docker run` or `docker compose`.

This leads to messy log files full of escape sequences such as this:

```
[38;5;247m[ [0m [38;5;45;1mINF [0m [38;5;247m]  [0m [39mDocker  [0m [38;5;45;1mStdOut [0m [39m:  [0m [38;5;45;1mrunning [0m
```

I am aware that [this package supports](https://github.com/serilog/serilog-sinks-console) `ConsoleTheme.None` to disable colorization, but we do not want to alter our code (or in the case of Nuke, cannot directly alter it), as then we would lose the nice coloring when running interactively on developer systems.

There are also important accessibility and compatibility reasons that people want to disable color. Colorblindness, or colors that conflict with terminal themes, etc.

The `NO_COLOR=1` environment variable has emerged as a de-facto standard for this, and is supported by a wide range of software. More information at https://no-color.org/

> To report a bug or request a feature, please give us as much information as possible, for example:
> - the exact package id and version you're using,
 `Serilog.Sinks.Console 5.0.1` - latest on Nuget.org at time of writing
  `Serilog.3.1.1` - latest on Nuget.org at time of writing
 
> - your `dotnet` toolchain version, target framework, and operating system,
` dotnet SDK 8.0.101, target framework net8.0, Windows 11

> - the current behavior, and

Build and run this small C# sample application.

```csharp
using Serilog;

var log = new LoggerConfiguration()
    .WriteTo.Console()
    .CreateLogger();

log.Information("Hello, {Name}!", Environment.UserName);
log.Warning("Today is {Today} and the number of the day is {Number}", DateTime.Now, 12);
```

> what you expect or want to happen instead.

When executed with the NO_COLOR env var set to 1, I expect to see no colors printed. 
But: I see colorized output
image

Thanks!

### PR DESCRIPTION
**Pull request by sungam3r**
fixes #153

### CODE REVIEW

**Comment by nblumhardt** [comment]
Awesome :+1:

**Comment by borland** [comment]
Thanks!

**Comment by rcdailey** [comment]
I tested this out but it doesn't work for me. Will this not work in combination with Serilog.Expressions?

**Comment by nblumhardt** [comment]
👍 Serilog.Expressions has its own theming implementation

**Pull request merged**
